config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :tasks, only: %w(index)

  namespace :api do
    resources :tasks, only: %w(index)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/api/tasks_controller.rb
class Api::TasksController < ApplicationController
  def index
    @tasks = Task.all
    render 'index', formats: 'json', handlers: 'jbuilder'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_datetime datetime
    datetime.strftime('%Y/%m/%d %H:%M:%S') if datetime.present?
  end
end

app/views/home/index.html.slim
h1 ToDoアプリケーション ホーム画面
= link_to 'タスク一覧へ', tasks_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_pack_tag 'hello_vue' %>
  </body>
</html>

app/views/tasks/index.html.slim
table
  thead
    tr
      th TITLE
      th DUE DATE
      th COMPLETE DATE
  tbody#tasks
    tr v-for="task in tasks"
      td = "{{ task.title }}"
      td = "{{ task.due_date }}"
      td = "{{ task.completed_at }}"
= javascript_pack_tag 'tasks'